# Generated by Django 5.2.4 on 2025-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', '食費'), ('transport', '交通費'), ('entertainment', '娯楽'), ('other', 'その他')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
